name: school
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.6.0-326.0.dev
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  sizer: ^3.0.0
  audioplayers: ^6.1.0
  just_audio: ^0.9.41
  buttons_tabbar: ^1.3.13
  http: ^1.2.2
  dartz: ^0.10.1
  lottie: ^3.1.3
  get_storage: ^2.1.1
  file_picker: ^8.1.3
  intl: ^0.19.0
  url_launcher: ^6.3.1
  open_file: ^3.5.10
  another_flutter_splash_screen: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
    - family: Gafata
      fonts:
        - asset: assets/fonts/gafata/Gafata-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/pacifico/Pacifico-Regular.ttf
    - family: Lemonada
      fonts:
        - asset: assets/fonts/lemondaa/Lemonada-VariableFont_wght.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
  